import { TProduct, TProductCategoryProps } from "../../types/types";

export const allProducts: TProduct[] = [
  {
    id: "asad",
    alterText: "Product 1",
    image: "/src/assets/images/headphone.png",
    originalPrice: 120,
    ratingAvg: 4.5,
    ratingCount: 42,
    salePrice: 99.99,
    tag: "Sale",
    title: "Wireless Headphones",
    category: "Sports & Outdoors",
  },
  {
    id: "rertt",
    alterText: "Product 2",
    image: "/src/assets/images/smartwatch.png",
    originalPrice: 0,
    ratingAvg: 5,
    ratingCount: 28,
    salePrice: 199.99,
    tag: "",
    title: "Smart Watch",
    category: "Sports & Outdoors",
  },
  {
    id: "adaweer",
    alterText: "Product 3",
    image: "/src/assets/images/bluetooth_speaker.png",
    originalPrice: 0,
    ratingAvg: 4.5,
    ratingCount: 17,
    salePrice: 79.99,
    tag: "New",
    title: "Bluetooth Speaker",
    category: "Electronics",
  },
  {
    id: "rtyikjl",
    alterText: "Product 4",
    image: "/src/assets/images/laptop_bag.png",
    originalPrice: 0,
    ratingAvg: 5,
    ratingCount: 35,
    salePrice: 49.99,
    tag: "",
    title: "Laptop Bag",
    category: "Electronics",
  },
];

export const allCategories: TProductCategoryProps[] = [
  {
    id: "asdcvw",
    alt: "Electronics Category",
    category: "Electronics",
    img: "/src/assets/images/electronics.png",
    linkTo: "pages/categories.html#electronics",
  },
  {
    id: "asdlkwe",
    alt: "Clothing Category",
    category: "Clothing",
    img: "/src/assets/images/clothing.png",
    linkTo: "pages/categories.html#clothing",
  },
  {
    id: "sdwerzaq",
    alt: "Home & Kitchen Category",
    category: "Home & Kitchen",
    img: "/src/assets/images/home_kitchen.png",
    linkTo: "pages/categories.html#home",
  },
  {
    id: "asdhyujkq",
    alt: "Sports & Outdoors Category",
    category: "Sports & Outdoors",
    img: "/src/assets/images/sports_outdoors.png",
    linkTo: "pages/categories.html#sports",
  },
];
